# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d36987d169036562ba66a4e07fa41179cbd1aa1e97fde1510529c6e4b878542fab5584bee1d1ce2cc415957811bd05f46329bafe862d86bfcff20092410bc7c

test:
  secret_key_base: 2f583328fcf868235dfec29b0f4779f769d8e669c49549c192c4b9dc1ecd694eb15f5de3110542f049732e1bed9c21b6940d64adf2e5315c6a8cf28d1b8120bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
